services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: retouches-megeve
    container_name: retouches-megeve
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - retouches-megeve
    env_file:
      - .env

networks:
  retouches-megeve:
    name: retouches-megeve

